/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Alerts for every facility in the caller's scope, most severe first.
         *     Without a status filter, returns alerts still needing attention
         *     (open and acknowledged)
         */
        get: operations["alert.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/{alert}/acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark an open alert as seen and being handled. No-op if already acknowledged */
        post: operations["alert.acknowledge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/{alert}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Close an alert. If the stock situation still holds, it is not raised
         *     again until it clears and recurs. No-op if already resolved
         */
        post: operations["alert.resolve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange credentials for a Sanctum bearer token */
        post: operations["auth.login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the token used for this request */
        post: operations["auth.logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The current user, their role, and the hierarchy node they are anchored at */
        get: operations["auth.me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/facilities/{facility}/delivery-notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A facility's delivery notes, newest first */
        get: operations["deliveryNote.index"];
        put?: never;
        /**
         * Create a delivery note — a draft, or confirmed straight away with
         *     confirm=true (the phone's reviewed scan). 201 when created; 200 with
         *     the existing note when client_reference repeats one already sent
         */
        post: operations["deliveryNote.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/delivery-notes/{deliveryNote}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["deliveryNote.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/delivery-notes/{deliveryNote}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post a draft's items to the ledger as receipts */
        post: operations["deliveryNote.confirm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/delivery-notes/{deliveryNote}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["deliveryNote.reject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/fcm-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register (or clear, with null) the push token of the device the user is
         *     signed in on. Tokens rotate, so the app sends it on every sign-in and
         *     foreground (mobile/CLAUDE.md rule 4)
         */
        post: operations["deviceToken.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lgas/{lga}/facilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Facilities in an LGA */
        get: operations["facility.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/facilities/{facility}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["facility.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/states/{state}/lgas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** LGAs in a state */
        get: operations["lga.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lgas/{lga}/stock-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * LGA rollup: totals per product, how many facilities carry each flag,
         *     and the facility drill-down list sorted worst-first
         * @description Computed live from stock_balances — fine at LGA scale, and it carries
         *     per-product batch detail. State/Federal aggregate facility_product_status.
         */
        get: operations["lgaStockSummary.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The product catalog. Not hierarchy-scoped: every role sees the same catalog */
        get: operations["product.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/facilities/{facility}/reorder-suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Quantity to order per product stocked at the facility: latest AMC
         *     snapshot against current usable stock. Products needing an order
         *     come first, lowest months of stock first
         */
        get: operations["reorderSuggestion.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/states/{state}/stock-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** State rollup: how many facilities carry each flag, per-product totals, and the LGAs worst first */
        get: operations["rollupSummary.state"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/federal/stock-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** National rollup: every state, worst first */
        get: operations["rollupSummary.federal"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/states": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** States visible to the caller (all for federal/admin, own state for state officers, none below that) */
        get: operations["state.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lgas/{lga}/stock-activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stock Card entries per week across the LGA's facilities the caller can see */
        get: operations["stockActivity.lga"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/states/{state}/stock-activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stock Card entries per week across the state's facilities the caller can see */
        get: operations["stockActivity.state"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/federal/stock-activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stock Card entries per week nationally */
        get: operations["stockActivity.federal"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/facilities/{facility}/stock-activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stock Card entries per week at one facility (received / issued / other) */
        get: operations["stockActivity.facility"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/facilities/{facility}/stock-balances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current stock at a facility: one entry per product with its batches,
         *     straight from stock_balances, plus usable/expired split and flags
         */
        get: operations["stockBalance.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/facilities/{facility}/stock-transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ledger history (the Stock Card) for a facility, paginated.
         *     With product_id and order=asc it reads exactly like the paper card
         */
        get: operations["stockTransaction.index"];
        put?: never;
        /**
         * Record a Stock Card entry. Authorization (StockTransactionPolicy@create)
         *     runs in StoreStockTransactionRequest::authorize(), before validation.
         *     201 when recorded; 200 with the existing entry when client_reference
         *     repeats one already recorded at this facility
         */
        post: operations["stockTransaction.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlertCollection */
        AlertCollection: components["schemas"]["AlertResource"][];
        /** AlertResource */
        AlertResource: {
            id: number;
            alert_type: components["schemas"]["AlertType"];
            severity: components["schemas"]["AlertSeverity"];
            status: components["schemas"]["AlertStatus"];
            /** @description False once the stock situation that raised the alert has cleared. */
            condition_active: boolean;
            facility: {
                id: number;
                name: string;
            };
            product: {
                id: number;
                name: string;
                sku: string;
                unit_of_measure: string;
            };
            /** @description Set for expiry alerts only. */
            batch: {
                id: number;
                batch_no: string;
                expiry_date: string;
            } | null;
            /** Format: date-time */
            created_at: string | null;
            /** Format: date-time */
            acknowledged_at: string | null;
            acknowledged_by_name: string | null;
            /** Format: date-time */
            resolved_at: string | null;
            /** @description Null when resolved automatically because the condition cleared. */
            resolved_by_name: string | null;
        };
        /**
         * AlertSeverity
         * @enum {string}
         */
        AlertSeverity: "info" | "warning" | "critical";
        /**
         * AlertStatus
         * @enum {string}
         */
        AlertStatus: "open" | "acknowledged" | "resolved";
        /**
         * AlertType
         * @description Same values as alerts.alert_type in docs/DATABASE_SCHEMA.md.
         * @enum {string}
         */
        AlertType: "stock_out" | "expired" | "low_stock" | "expiring_soon";
        /** AreaStockSummaryResource */
        AreaStockSummaryResource: {
            /** @enum {string} */
            level: "lga" | "state";
            id: number;
            name: string;
            /** @description States only. */
            geopolitical_zone: string | null;
            facility_count: number;
            /** @description Facilities with at least one product on the Stock Card. */
            reporting_facility_count: number;
            /** @description Number of facilities with at least one product carrying each flag. */
            flag_counts: {
                stock_out: number;
                expired: number;
                low_stock: number;
                expiring_soon: number;
            };
            /** @description Facilities with at least one product at or below reorder level. */
            needs_reorder_count: number;
            last_transaction_date: string | null;
            /** @description Products stocked out at the most facilities here, top 3. */
            stock_out_products: {
                product: {
                    id: number;
                    name: string;
                    sku: string;
                };
                facility_count: number;
            }[];
        };
        /** BatchStockResource */
        BatchStockResource: {
            batch_id: number | null;
            batch_no: string | null;
            expiry_date: string | null;
            expiry_status: components["schemas"]["ExpiryStatus"] | null;
            quantity_on_hand: number;
            last_transaction_id: number;
        };
        /** DeliveryNoteCollection */
        DeliveryNoteCollection: components["schemas"]["DeliveryNoteResource"][];
        /** DeliveryNoteResource */
        DeliveryNoteResource: {
            id: number;
            facility_id: number;
            delivery_note_no: string | null;
            source: string;
            received_date: string;
            status: components["schemas"]["DeliveryNoteStatus"];
            /** @enum {string} */
            capture_method: "manual" | "ocr";
            comments: string | null;
            client_reference: string | null;
            created_by_name: string;
            confirmed_by_name: string | null;
            /** Format: date-time */
            confirmed_at: string | null;
            rejected_by_name: string | null;
            /** Format: date-time */
            rejected_at: string | null;
            rejection_reason: string | null;
            /** Format: date-time */
            created_at: string | null;
            items: {
                id: number;
                product: {
                    id: number;
                    name: string;
                    sku: string;
                    unit_of_measure: string;
                };
                batch_no: string | null;
                expiry_date: string | null;
                quantity: number;
                /** @description The receipt this line became, once confirmed. */
                stock_transaction_id: number | null;
            }[];
        };
        /**
         * DeliveryNoteStatus
         * @enum {string}
         */
        DeliveryNoteStatus: "draft" | "confirmed" | "rejected";
        /**
         * ExpiryStatus
         * @enum {string}
         */
        ExpiryStatus: "ok" | "expiring_soon" | "expired";
        /** FacilityResource */
        FacilityResource: {
            id: number;
            name: string;
            type: string;
            address: string | null;
            latitude: string | null;
            longitude: string | null;
            phone: string | null;
            is_active: boolean;
            lga: {
                id: number;
                name: string;
            };
            state: {
                id: number;
                name: string;
            };
        };
        /** FacilityStockSummaryResource */
        FacilityStockSummaryResource: {
            /** @constant */
            level: "facility";
            id: number;
            name: string;
            type: string;
            is_active: boolean;
            product_count: number;
            /** @description Date of the facility's most recent Stock Card entry, if any. */
            last_transaction_date: string | null;
            /** @description Number of this facility's products carrying each flag. */
            flag_counts: {
                stock_out: number;
                expired: number;
                low_stock: number;
                expiring_soon: number;
            };
            /** @description Products at or below reorder level (includes low stock and stock-outs). */
            needs_reorder_count: number;
            /** @description Products with any flag or at/below reorder level. */
            flagged_products: components["schemas"]["ProductStockResource"][];
        };
        /** LgaResource */
        LgaResource: {
            id: number;
            state_id: number;
            name: string;
        };
        /** ProductResource */
        ProductResource: {
            id: number;
            name: string;
            sku: string;
            category: string;
            unit_of_measure: string;
            requires_batch_tracking: boolean;
            requires_cold_chain: boolean;
            min_stock_level: number;
            max_stock_level: number;
            reorder_level: number;
            is_active: boolean;
        };
        /** ProductRollupResource */
        ProductRollupResource: {
            product: components["schemas"]["ProductResource"];
            quantity_on_hand: number;
            usable_quantity: number;
            expired_quantity: number;
            /** @description Number of facilities where this product carries each flag. */
            facility_counts: {
                stock_out: number;
                expired: number;
                low_stock: number;
                expiring_soon: number;
            };
            /** @description Facilities where this product is at or below reorder level. */
            facilities_needing_reorder: number;
        };
        /** ProductStockResource */
        ProductStockResource: {
            product: components["schemas"]["ProductResource"];
            /** @description Sum of stock_balances.quantity_on_hand across batches, including expired stock. */
            quantity_on_hand: number;
            /** @description On hand minus expired batches; thresholds are judged on this. */
            usable_quantity: number;
            expired_quantity: number;
            expiring_soon_quantity: number;
            level: components["schemas"]["StockLevel"];
            /** @description Most severe first. */
            flags: components["schemas"]["AlertType"][];
            /** @description Earliest expiry first. */
            batches: components["schemas"]["BatchStockResource"][];
        };
        /** ReorderSuggestionResource */
        ReorderSuggestionResource: {
            product: components["schemas"]["ProductResource"];
            usable_quantity: number;
            level: components["schemas"]["StockLevel"];
            /** @description Average Monthly Consumption (issues per month); null without a complete month of history. */
            amc_quantity: number | null;
            /** @description Complete months the AMC is averaged over. */
            amc_months_used: number;
            /** @description Month of the AMC snapshot used (YYYY-MM-DD, first of month); null if none computed yet. */
            amc_period_month: string | null;
            /** @description Usable stock divided by AMC; null without an AMC. */
            months_of_stock: number | null;
            /** @description Target stock level: AMC x max months, or the product's max_stock_level without an AMC. */
            max_stock_quantity: number;
            /** @enum {string} */
            basis: "amc" | "product_max";
            /** @description Max stock minus usable stock, never negative. */
            suggested_quantity: number;
        };
        /** StateResource */
        StateResource: {
            id: number;
            name: string;
            geopolitical_zone: string;
        };
        /**
         * StockLevel
         * @description Where a product's *usable* (unexpired) quantity sits against its thresholds — the Bin Card's Min SL / EOP columns.
         * @enum {string}
         */
        StockLevel: "stock_out" | "low_stock" | "reorder" | "ok";
        /** StockTransactionCollection */
        StockTransactionCollection: components["schemas"]["StockTransactionResource"][];
        /** StockTransactionResource */
        StockTransactionResource: {
            id: number;
            facility_id: number;
            product_id: number;
            batch_id: number | null;
            batch_no: string | null;
            expiry_date: string | null;
            transaction_date: string;
            transaction_type: components["schemas"]["TransactionType"];
            quantity: number;
            running_balance: number;
            voucher_no: string | null;
            counterparty: string | null;
            comments: string | null;
            performed_by: number;
            performed_by_name: string;
            product_name: string;
            delivery_note_id: number | null;
            /** @description The client's idempotency key, if it sent one. */
            client_reference: string | null;
            /** Format: date-time */
            created_at: string | null;
        };
        /**
         * StoreDeliveryNoteRequest
         * @description Shape validation for POST /facilities/{facility}/delivery-notes. Ledger
         *     rules (known batch expiry, back-dating) are checked when the note is
         *     confirmed, by StockLedgerService.
         */
        StoreDeliveryNoteRequest: {
            delivery_note_no?: string | null;
            /** @description Supplier or warehouse; becomes the receipts' "Received from". */
            source: string;
            /** Format: date */
            received_date: string;
            /**
             * @description "ocr" when the lines were read from a photo on the device and reviewed by staff.
             * @enum {string|null}
             */
            capture_method?: "manual" | "ocr" | null;
            comments?: string | null;
            /** @description Confirm straight away (post the receipts) instead of saving a draft. */
            confirm?: boolean | null;
            /** @description Idempotency key: re-sending it returns the note already created. */
            client_reference?: string | null;
            items: {
                product_id: number;
                batch_no?: string | null;
                /** Format: date */
                expiry_date?: string | null;
                quantity: number;
            }[];
        };
        /**
         * StoreStockTransactionRequest
         * @description Shape validation for POST /facilities/{facility}/stock-transactions.
         *     State-dependent checks (unknown batch, insufficient stock, back-dating)
         *     live in StockLedgerService and also come back as 422s.
         */
        StoreStockTransactionRequest: {
            product_id: number;
            transaction_type: components["schemas"]["TransactionType"];
            quantity: number;
            batch_no?: string | null;
            /** Format: date */
            expiry_date?: string | null;
            voucher_no?: string | null;
            counterparty?: string | null;
            comments?: string | null;
            /** @description Idempotency key (e.g. a UUID from an offline outbox). Re-sending it returns the entry already recorded. */
            client_reference?: string | null;
            /** Format: date */
            transaction_date: string;
        };
        /**
         * TransactionType
         * @description Stock Card row types. quantity is always >= 0; the direction comes from the type. This is the single definition of how each type moves a balance — StockLedgerService and ReconcileStockBalances both go through apply().
         * @enum {string}
         */
        TransactionType: "receipt" | "issue" | "loss" | "adjustment_in" | "adjustment_out" | "physical_count" | "transfer_in" | "transfer_out";
        /** UserResource */
        UserResource: {
            id: number;
            name: string;
            email: string;
            role: components["schemas"]["UserRole"];
            facility_id: number | null;
            lga_id: number | null;
            state_id: number | null;
            /** @description The hierarchy node this account is anchored at; drives which dashboard the client opens. */
            node: {
                /** @enum {string} */
                level: "facility" | "lga" | "state" | "national";
                id: number | null;
                name: string;
                path: string[];
            };
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "sdp_staff" | "lga_officer" | "state_officer" | "federal_officer" | "admin";
    };
    responses: {
        /** @description Validation error */
        ValidationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Errors overview. */
                    message: string;
                    /** @description A detailed description of each field that failed validation. */
                    errors: {
                        [key: string]: string[];
                    };
                };
            };
        };
        /** @description Unauthenticated */
        AuthenticationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Error overview. */
                    message: string;
                };
            };
        };
        /** @description Authorization error */
        AuthorizationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Error overview. */
                    message: string;
                };
            };
        };
        /** @description Not found */
        ModelNotFoundException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Error overview. */
                    message: string;
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "alert.index": {
        parameters: {
            query?: {
                status?: components["schemas"]["AlertStatus"] | null;
                alert_type?: components["schemas"]["AlertType"] | null;
                severity?: components["schemas"]["AlertSeverity"] | null;
                /** @description Narrow to one facility within your scope. */
                facility_id?: number | null;
                per_page?: number | null;
                page?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated set of `AlertResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AlertCollection"];
                        meta: {
                            pagination: {
                                current_page: number;
                                /** @description Number of items shown per page. */
                                per_page: number;
                                /** @description Total number of items being paginated. */
                                total: number;
                                last_page: number;
                            };
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "alert.acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The alert ID */
                alert: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `AlertResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AlertResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "alert.resolve": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The alert ID */
                alert: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `AlertResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AlertResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "auth.login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    password: string;
                    /** @description Label for the token, e.g. "web" or a phone model. */
                    device_name?: string | null;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            token: string;
                            user: components["schemas"]["UserResource"];
                        };
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "auth.logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "auth.me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `UserResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["UserResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "deliveryNote.index": {
        parameters: {
            query?: {
                status?: components["schemas"]["DeliveryNoteStatus"] | null;
                per_page?: number | null;
                page?: number | null;
            };
            header?: never;
            path: {
                /** @description The facility ID */
                facility: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated set of `DeliveryNoteResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["DeliveryNoteCollection"];
                        meta: {
                            pagination: {
                                current_page: number;
                                /** @description Number of items shown per page. */
                                per_page: number;
                                /** @description Total number of items being paginated. */
                                total: number;
                                last_page: number;
                            };
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "deliveryNote.store": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The facility ID */
                facility: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreDeliveryNoteRequest"];
            };
        };
        responses: {
            /** @description `DeliveryNoteResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["DeliveryNoteResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "deliveryNote.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The delivery note ID */
                deliveryNote: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `DeliveryNoteResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["DeliveryNoteResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "deliveryNote.confirm": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The delivery note ID */
                deliveryNote: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `DeliveryNoteResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["DeliveryNoteResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "deliveryNote.reject": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The delivery note ID */
                deliveryNote: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    reason?: string | null;
                };
            };
        };
        responses: {
            /** @description `DeliveryNoteResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["DeliveryNoteResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "deviceToken.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description FCM registration token; null to stop pushes to this user (e.g. on sign-out). */
                    token: string | null;
                };
            };
        };
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "facility.index": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The lga ID */
                lga: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `FacilityResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["FacilityResource"][];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "facility.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The facility ID */
                facility: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `FacilityResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["FacilityResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "lga.index": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The state ID */
                state: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `LgaResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["LgaResource"][];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "lgaStockSummary.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The lga ID */
                lga: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            node: {
                                /** @constant */
                                level: "lga";
                                id: number;
                                name: string;
                                parent: {
                                    /** @constant */
                                    level: "state";
                                    id: number;
                                    name: string;
                                };
                            };
                            child_count: number;
                            /** @description Same as child_count here; the facility total at State and Federal level. */
                            facility_count: number;
                            /** @description Number of child facilities with at least one product carrying each flag. */
                            facility_counts: {
                                stock_out: number;
                                expired: number;
                                low_stock: number;
                                expiring_soon: number;
                            };
                            /** @description Facilities by their most serious issue, each counted once. */
                            facility_status: {
                                stock_out: number;
                                low_stock: number;
                                reorder: number;
                                ok: number;
                                no_data: number;
                            };
                            products: components["schemas"]["ProductRollupResource"][];
                            /** @description Child facilities, worst first. */
                            children: components["schemas"]["FacilityStockSummaryResource"][];
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "product.index": {
        parameters: {
            query?: {
                category?: string | null;
                is_active?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `ProductResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ProductResource"][];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "reorderSuggestion.index": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The facility ID */
                facility: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `ReorderSuggestionResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ReorderSuggestionResource"][];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "rollupSummary.state": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The state ID */
                state: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            node: {
                                /** @constant */
                                level: "state";
                                id: number;
                                name: string;
                                parent: {
                                    /** @constant */
                                    level: "country";
                                    id: null;
                                    /** @constant */
                                    name: "Nigeria";
                                };
                            };
                            child_count: number;
                            facility_count: number;
                            /** @description Number of facilities with at least one product carrying each flag. */
                            facility_counts: {
                                stock_out: number;
                                expired: number;
                                low_stock: number;
                                expiring_soon: number;
                            };
                            /** @description Facilities by their most serious issue, each counted once. */
                            facility_status: {
                                stock_out: number;
                                low_stock: number;
                                reorder: number;
                                ok: number;
                                no_data: number;
                            };
                            products: components["schemas"]["ProductRollupResource"][];
                            /** @description Child LGAs, worst first. */
                            children: components["schemas"]["AreaStockSummaryResource"][];
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "rollupSummary.federal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            node: {
                                /** @constant */
                                level: "country";
                                id: null;
                                /** @constant */
                                name: "Nigeria";
                                parent: null;
                            };
                            child_count: number;
                            facility_count: number;
                            /** @description Number of facilities with at least one product carrying each flag. */
                            facility_counts: {
                                stock_out: number;
                                expired: number;
                                low_stock: number;
                                expiring_soon: number;
                            };
                            /** @description Facilities by their most serious issue, each counted once. */
                            facility_status: {
                                stock_out: number;
                                low_stock: number;
                                reorder: number;
                                ok: number;
                                no_data: number;
                            };
                            products: components["schemas"]["ProductRollupResource"][];
                            /** @description Child states, worst first. */
                            children: components["schemas"]["AreaStockSummaryResource"][];
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
        };
    };
    "state.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `StateResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["StateResource"][];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "stockActivity.lga": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The lga ID */
                lga: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            weeks: ({
                                week_start: string | unknown;
                            } & {
                                [key: string]: unknown;
                            })[];
                            totals: {
                                received: number;
                                issued: number;
                                other: number;
                            };
                            last_transaction_date: string | null;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "stockActivity.state": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The state ID */
                state: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            weeks: ({
                                week_start: string | unknown;
                            } & {
                                [key: string]: unknown;
                            })[];
                            totals: {
                                received: number;
                                issued: number;
                                other: number;
                            };
                            last_transaction_date: string | null;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "stockActivity.federal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            weeks: ({
                                week_start: string | unknown;
                            } & {
                                [key: string]: unknown;
                            })[];
                            totals: {
                                received: number;
                                issued: number;
                                other: number;
                            };
                            last_transaction_date: string | null;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
        };
    };
    "stockActivity.facility": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The facility ID */
                facility: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            weeks: ({
                                week_start: string | unknown;
                            } & {
                                [key: string]: unknown;
                            })[];
                            totals: {
                                received: number;
                                issued: number;
                                other: number;
                            };
                            last_transaction_date: string | null;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "stockBalance.index": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The facility ID */
                facility: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `ProductStockResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ProductStockResource"][];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "stockTransaction.index": {
        parameters: {
            query?: {
                product_id?: number | null;
                transaction_type?: components["schemas"]["TransactionType"] | null;
                /** @description Inclusive, YYYY-MM-DD. */
                from?: string | null;
                /** @description Inclusive, YYYY-MM-DD. */
                to?: string | null;
                /** @description Default desc (newest first). */
                order?: "asc" | "desc" | null;
                per_page?: number | null;
                page?: number | null;
            };
            header?: never;
            path: {
                /** @description The facility ID */
                facility: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated set of `StockTransactionResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["StockTransactionCollection"];
                        meta: {
                            pagination: {
                                current_page: number;
                                /** @description Number of items shown per page. */
                                per_page: number;
                                /** @description Total number of items being paginated. */
                                total: number;
                                last_page: number;
                            };
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "stockTransaction.store": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The facility ID */
                facility: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreStockTransactionRequest"];
            };
        };
        responses: {
            /** @description `StockTransactionResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["StockTransactionResource"];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
}
